## Data Science for Social Impact 
# Homework Monday: Python Basics, Lists, and Arrays

Please complete this notebook by filling in the cells provided. The solved homework should be uploaded to Gradescope on Canvas.

#### Deadline:

This assignment is due on **Monday at 11:30pm**.

Directly sharing answers is not okay, but discussing problems with eachother is encouraged!


In [17]:
# Don't change this cell; just run it. 

import numpy as np

## Data Types

**Question 1.** When would you make a string using " " instead of ' '?

If you want to create a string and use certain characters that would otherwise be misinterpreted by Python (i.e. use escape sequences as string modifiers). In particular, if you want to use an apostrophe.

**Question 2.** What data type would you use to represent your bill at a restaurant?

Float (allows for cents)

**Question 3.** What data type would you use to represent whether a number is even or odd?

Boolean (True or False)

**Question 4.** Use a function to print the data type of the following variable:

In [1]:
my_variable = '8.3'

In [2]:
type(my_variable)

str

**Question 5.** Use a function to convert `my_variable` into a float.

In [4]:
type(float(my_variable))

float

# Strings and Lists

Consider the list below:

In [5]:
my_words = ["My", "I", "This", 'a', "She", 7, """am""", 89, "is", 'sentence', 'cup', 'dog', 'cute', 'love', '.', '!' ]

**Question 6.** Extract and slice from the list my_words to create the sentence: "This is a sentence." You can use list methods or operations.

In [9]:
print(my_words[2] + " " + my_words[8] + " " + my_words[3] + " " + my_words[9] + my_words[14])

This is a sentence.


In [11]:
print(my_words[2], my_words[8], my_words[3], my_words[9] + my_words[14])

This is a sentence.


**Question 7.** Create an interesting sentence from my_words

In [15]:
print(my_words[0], my_words[11], my_words[8], str(my_words[5]) + my_words[15])

My dog is 7!


**Question 8.** Use the *replace* function for strings to change the string *'machine learning'* into the string *'learning machine'*. You must do everything into one line of code and you can only replace one full word with a different full word. An example of using *replace* twice in one line of code is below. [Note: the output should be a string of the same length as the one you started with; no extra spaces etc.] 

In [ ]:
# this cell illustrates the use of .replace 
'Today is a good day.'.replace('.','!')

In [ ]:
# this cell illustrates the use of .replace twice
'on campus'.replace('on','happy').replace('campus','place')

In [2]:
#Q8 code here
'machine learning'.replace('machine', 'pre').replace('learning', 'machine').replace('pre', 'learning')

'learning machine'

# Puzzles with Arrays

**Question 9.** Replace the ellipses in the following code to get the result 86

In [28]:
my_array = np.array([1,2,3,4])
my_array2 = my_array * 5
my_array3 = my_array2 + 9
sum(my_array3)

86

**Question 10.** 

**a.** Create an array containing every 6th number between 7 and 700 inclusive (Hint: please do not type all of these numbers, use a function). 

**b.** Find the remainder after dividing each number by 7 (Hint: what operator can you use here). 

**c.** Then, take the average of the resulting numbers.

In [2]:
#a
array1 = np.arange(7, 701, 6)
#b
array2 = array1 % 7
#c
np.mean(array2)

3.0258620689655173

**Question 11.** 

**a.** Create an array called `four` that includes all integers from 4 to 120 (inclusive) in intervals of 4

**b.** Alter `four` to be a 5x6 array. Print the result.

**c.** Write code to select the highlighted numbers:

<br>

<div>
<img src="https://raw.githubusercontent.com/campbelle1/Introduction-to-Data-Science/main/Week%202/Array-exercise2.png"/>
</div>

In [5]:
#a
four = np.arange(4, 121, 4)
#b
four_re = np.reshape(four, (5, 6))
#c1
four_re[::2,::2]

array([[  4,  12,  20],
       [ 52,  60,  68],
       [100, 108, 116]])

In [31]:
#c2
four_re[:, [1, 3, 5]]

array([[  8,  16,  24],
       [ 32,  40,  48],
       [ 56,  64,  72],
       [ 80,  88,  96],
       [104, 112, 120]])

In [32]:
#c3
four_re[[0, 2, 4],:]

array([[  4,   8,  12,  16,  20,  24],
       [ 52,  56,  60,  64,  68,  72],
       [100, 104, 108, 112, 116, 120]])

**Question 12.** Sally is 5 ft 3in, 120 lbs. Create an expression that uses two variables: one called `height` (which equates to the value of Sally's height in inches) and called `weight` (which equates to the value of Sally's weight, in pounds). Using these variables, to calculate a Sally's BMI. The formula for BMI calculations are as follows:

weight (kg) ÷ height^2 (meters) * 703

**Correction to weight (lb) + height^2 (inches)*703**

Assign this calculation as `bmi`. <u>In one line of code</u>, print a statement that says:

"The BMI of this person is:

`bmi`."

In [31]:
height = 63
weight = 120
bmi = (weight) / (height)**2 * 703
print('The BMI of this person is:', bmi)

The BMI of this person is: 21.25472411186697
